export const mockCustomers = [
  {
    id: "c1",
    firstName: "Sarah",
    lastName: "Chen",
    email: "sarah.chen@email.com",
    phone: "+65 9123 4567",
    status: "active",
    tags: ["VIP", "Referral"],
    company: "Fintech Pte Ltd",
    notes: "Referred by Marcus. Interested in the enterprise plan.",
    createdAt: "2024-03-12",
  },
  {
    id: "c2",
    firstName: "James",
    lastName: "Tan",
    email: "james.tan@email.com",
    phone: "+65 9234 5678",
    status: "active",
    tags: ["Lead"],
    company: "Builders Co",
    notes: "Met at the PropTech conference. Follow up in Q3.",
    createdAt: "2024-06-01",
  },
  {
    id: "c3",
    firstName: "Nurul",
    lastName: "Huda",
    email: "nurul.huda@email.com",
    phone: "+65 9345 6789",
    status: "inactive",
    tags: [],
    company: "Gov Agency",
    notes: "",
    createdAt: "2024-01-20",
  },
  {
    id: "c4",
    firstName: "Marcus",
    lastName: "Lim",
    email: "marcus.lim@email.com",
    phone: "+65 9456 7890",
    status: "active",
    tags: ["Lead", "VIP"],
    company: "RetailX Pte Ltd",
    notes: "High-value account. Has requested a custom SLA.",
    createdAt: "2023-11-05",
  },
  {
    id: "c5",
    firstName: "Wei Ling",
    lastName: "Goh",
    email: "weiling.goh@email.com",
    phone: "+65 9567 8901",
    status: "active",
    tags: ["Referral"],
    company: "HealthTech SG",
    notes: "Referred by Sarah Chen.",
    createdAt: "2024-08-19",
  },
];

// Helper to generate unique IDs
export const generateCustomerId = () => "c" + Date.now();